'use strict';
const $=id=>document.getElementById(id);let app={me:null,providers:[],profiles:[],sessions:[]};
async function api(path,options={}){const response=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});if(response.status===204)return null;const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||`HTTP ${response.status}`);return body}
function notify(message,good=false){$('notice').textContent=message;$('notice').classList.toggle('good',good);$('notice').hidden=false;setTimeout(()=>$('notice').hidden=true,6000)}
async function copy(value){try{await navigator.clipboard.writeText(value);notify('Ссылка скопирована',true)}catch(_){prompt('Скопируйте ссылку',value)}}
function modeName(mode){return({vk:'VK Video',wbstream:'WB Stream',telemost:'Telemost',dion:'Dion'})[mode]||mode}
function render(){const logged=!!app.me;$('auth').hidden=logged;$('workspace').hidden=!logged;$('logout').hidden=!logged;if(!logged)return;$('username').textContent=app.me.username;$('profileCount').textContent=app.profiles.length;$('profiles').innerHTML=app.profiles.length?app.profiles.map(p=>`<div class="row"><div><h3>${escapeHTML(p.name)}</h3><p>${escapeHTML(modeName(p.config.mode))}</p></div><div class="actions"><button data-start="${p.id}">Запустить</button><button class="quiet" data-mobile="${p.id}">В Android</button><button class="quiet" data-edit="${p.id}">Изменить</button><button class="quiet danger" data-delete="${p.id}">Удалить</button></div></div>`).join(''):'<p class="empty">Профилей пока нет.</p>';$('sessions').innerHTML=app.sessions.length?app.sessions.map(s=>`<div class="row"><div><h3>${escapeHTML(s.clientName)}</h3><p><span class="state">${escapeHTML(s.status.state)}</span> · ${escapeHTML(modeName(s.status.mode))}</p></div><div class="actions">${s.status.sessionLink?`<button class="quiet" data-link="${s.id}">Ссылка</button>`:''}${['stopped','failed'].includes(s.status.state)?'':`<button class="quiet danger" data-stop="${s.id}">Остановить</button>`}</div></div>`).join(''):'<p class="empty">Запущенных сессий нет.</p>';bindRows()}
function escapeHTML(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c])}
function bindRows(){document.querySelectorAll('[data-start]').forEach(b=>b.onclick=()=>run(async()=>{await api('/api/user/sessions',{method:'POST',body:JSON.stringify({clientId:b.dataset.start})});await refresh()}));document.querySelectorAll('[data-stop]').forEach(b=>b.onclick=()=>run(async()=>{await api(`/api/user/sessions/${b.dataset.stop}/stop`,{method:'POST',body:'{}'});await refresh()}));document.querySelectorAll('[data-link]').forEach(b=>b.onclick=()=>{const s=app.sessions.find(x=>x.id===b.dataset.link);if(s?.status.sessionLink)copy(s.status.sessionLink)});document.querySelectorAll('[data-mobile]').forEach(b=>b.onclick=()=>run(async()=>{const result=await api(`/api/user/profiles/${b.dataset.mobile}/mobile-invite`,{method:'POST',body:'{}'});await copy(result.url)}));document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditor(app.profiles.find(x=>x.id===b.dataset.edit)));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>run(async()=>{if(!confirm('Удалить профиль?'))return;await api(`/api/user/profiles/${b.dataset.delete}`,{method:'DELETE'});await refresh()}))}
async function refresh(){[app.profiles,app.sessions]=await Promise.all([api('/api/user/profiles'),api('/api/user/sessions')]);render()}
function inviteToken(){return new URLSearchParams(location.hash.slice(1)).get('invite')||''}
async function boot(){const invite=inviteToken();$('signupCard').hidden=!invite;try{app.me=await api('/api/user/me');app.providers=(await api('/api/user/providers')).filter(p=>p.configured);fillProviders();await refresh()}catch(_){app.me=null;render()}}
function fillProviders(){ $('provider').innerHTML=app.providers.map(p=>`<option value="${p.id}">${escapeHTML(p.name)}</option>`).join('')||'<option value="">Нет настроенных провайдеров</option>'}
function openEditor(profile=null){$('editor').hidden=false;$('editorTitle').textContent=profile?'Изменить профиль':'Новый профиль';$('profileId').value=profile?.id||'';$('profileName').value=profile?.name||'';$('provider').value=profile?.config.mode||app.providers[0]?.id||'';$('profileName').focus()}
async function run(action){try{await action()}catch(error){notify(error.message)}}
$('loginForm').onsubmit=e=>{e.preventDefault();run(async()=>{app.me=await api('/api/user/login',{method:'POST',body:JSON.stringify({username:$('loginName').value,password:$('loginPassword').value})});app.providers=(await api('/api/user/providers')).filter(p=>p.configured);fillProviders();await refresh()})};
$('signupForm').onsubmit=e=>{e.preventDefault();run(async()=>{app.me=await api('/api/user/register',{method:'POST',body:JSON.stringify({invite:inviteToken(),username:$('signupName').value,password:$('signupPassword').value})});history.replaceState({},'', '/portal');app.providers=(await api('/api/user/providers')).filter(p=>p.configured);fillProviders();await refresh()})};
$('profileForm').onsubmit=e=>{e.preventDefault();run(async()=>{const id=$('profileId').value;await api(id?`/api/user/profiles/${id}`:'/api/user/profiles',{method:id?'PATCH':'POST',body:JSON.stringify({name:$('profileName').value,config:{mode:$('provider').value}})});$('editor').hidden=true;await refresh()})};
$('newProfile').onclick=()=>openEditor();$('closeEditor').onclick=()=>$('editor').hidden=true;$('refresh').onclick=()=>run(refresh);$('logout').onclick=()=>run(async()=>{await api('/api/user/logout',{method:'POST',body:'{}'});app.me=null;render()});boot();
